# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/kbm5393/Downloads/project_1-1/project_1111/project_1111.cache/wt [current_project]
set_property parent.project_path C:/Users/kbm5393/Downloads/project_1-1/project_1111/project_1111.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Users/kbm5393/Downloads/project_1-1/project_1111/project_1111.srcs/sources_1/new/MUX_32bit.v
  C:/Users/kbm5393/Downloads/project_1-1/project_1111/project_1111.srcs/sources_1/new/ALU.v
  C:/Users/kbm5393/Downloads/project_1-1/project_1111/project_1111.srcs/sources_1/new/sign_extension.v
  C:/Users/kbm5393/Downloads/project_1-1/project_1111/project_1111.srcs/sources_1/new/registerfile.v
  C:/Users/kbm5393/Downloads/project_1-1/project_1111/project_1111.srcs/sources_1/new/MUX.v
  C:/Users/kbm5393/Downloads/project_1-1/project_1111/project_1111.srcs/sources_1/new/Control_Unit.v
  C:/Users/kbm5393/Downloads/project_1-1/project_1111/project_1111.srcs/sources_1/new/DataMem.v
  C:/Users/kbm5393/Downloads/project_1-1/project_1111/project_1111.srcs/sources_1/new/WB.v
  C:/Users/kbm5393/Downloads/project_1-1/project_1111/project_1111.srcs/sources_1/new/MEM.v
  C:/Users/kbm5393/Downloads/project_1-1/project_1111/project_1111.srcs/sources_1/new/EXE.v
  C:/Users/kbm5393/Downloads/project_1-1/project_1111/project_1111.srcs/sources_1/new/ID.v
  C:/Users/kbm5393/Downloads/project_1-1/project_1111/project_1111.srcs/sources_1/new/IF.v
  C:/Users/kbm5393/Downloads/project_1-1/project_1111/project_1111.srcs/sources_1/new/cpu.v
}
read_xdc C:/Users/kbm5393/Downloads/VivadoDemo/VivadoDemo/ZYBO_MASTER.xdc
set_property used_in_implementation false [get_files C:/Users/kbm5393/Downloads/VivadoDemo/VivadoDemo/ZYBO_MASTER.xdc]

synth_design -top cpu -part xc7z010clg400-1
write_checkpoint -noxdef cpu.dcp
catch { report_utilization -file cpu_utilization_synth.rpt -pb cpu_utilization_synth.pb }
